"""Generates the profile README.md from config.py and the section list."""
from __future__ import annotations

import os

import config as C

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))

ALT = {
    "hero": "Paarth Gupta — AI and full-stack engineer (LLMs, RAG, agentic AI, Next.js, Node.js), open to internships. "
            "An animated chat answers recruiter questions with retrieval over his résumé.",
    "layers": "Every layer of an AI product, each shipped in a real project: interface (Next.js, React, TypeScript), "
              "API (Node.js, Express, FastAPI), agents (LangGraph, LangChain), retrieval (RAG, Qdrant, ChromaDB, sqlite-vec), "
              "data (PostgreSQL, Prisma, Drizzle, Supabase) and models (Groq, Ollama).",
    "modelcard": "Model card for Paarth: intended use as an AI or full-stack intern; B.Tech CSE at KIET (CGPA 8.57) and "
                 "Language Metrics; LeetCode 1400+, Quackathon 2026 track winner, Oracle Agentic AI certified.",
    "embed": "Skills as an embedding space: an LLM/RAG/agents cluster and a full-stack web cluster, bridged by Python, "
             "FastAPI and SSE. The query 'AI + full-stack intern' lands between them.",
    "experience": "Full Stack Developer Intern at Language Metrics since August 2026: teacher and admin portals, JWT auth, "
                  "class booking, Razorpay checkout, coin wallet, versioned REST APIs, Prisma query tuning.",
    "evidence": "Six repositories: MandateOS and ClauseGuard (live), Knowledge-Agent, TrueBrain, PromptForge, Drishti.",
    "skyline": "My GitHub contributions over the last 52 weeks as an isometric city. Updated daily.",
    "footer": "Your turn — send a prompt: email Paarth.",
}


def img(src: str, alt: str) -> str:
    return f'<img src="assets/{src}" width="100%" alt="{alt}">'


def head(slug: str, alt: str) -> str:
    return (f'<picture><source media="(prefers-color-scheme: dark)" srcset="assets/h-{slug}.svg">'
            f'<img src="assets/h-{slug}-light.svg" width="100%" alt="{alt}"></picture>')


def build_all():
    mail = f"mailto:{C.EMAIL}"
    r = C.repo
    out = []
    w = out.append
    w("<!--\n  Generated by .github/profile/build_all.py — edit .github/profile/config.py or the\n"
      "  files in .github/profile/sections/ and push; the rebuild workflow regenerates everything.\n-->\n")
    w(f'<p align="center">{img("hero.svg", ALT["hero"])}</p>\n')
    w('<p align="center">'
      f'<a href="{mail}"><img src="assets/btn-email.svg" height="44" alt="Email me"></a>&nbsp;&nbsp;'
      f'<a href="{C.LINKEDIN}"><img src="assets/btn-linkedin.svg" height="44" alt="LinkedIn"></a>&nbsp;&nbsp;'
      f'<a href="{C.LEETCODE}"><img src="assets/btn-leetcode.svg" height="44" alt="LeetCode"></a>&nbsp;&nbsp;'
      f'<a href="{C.portfolio()}"><img src="assets/btn-portfolio.svg" height="44" alt="Portfolio"></a></p>\n')
    w("<br>\n")
    w("**I'm Paarth, and I build AI products end to end.** LLM features with retrieval and agents underneath, and "
      "the Next.js + Node apps that put them in front of real users. By day I'm a full-stack intern at "
      f"[Language Metrics]({C.LANGUAGE_METRICS}), shipping to a live SaaS. I'm a third-year CSE student at KIET "
      "(CGPA 8.57), a Quackathon 2026 track winner, and certified in agentic AI by Oracle.\n")
    w("**AI** — LLMs, RAG (Qdrant, ChromaDB, sqlite-vec), agentic AI (LangGraph, LangChain), local models (Ollama), evals (RAGAS)<br>\n"
      "**Full-stack** — Next.js, React, TypeScript, Node.js, Express, FastAPI, PostgreSQL + Prisma, JWT / RBAC, payments<br>\n"
      f"**Shipping now** — the Teacher & Admin portals behind [languagemetrics.in]({C.LANGUAGE_METRICS})<br>\n"
      f"**Looking for** — AI engineering and full-stack internships. [Email me]({mail}).\n")
    w("<br>\n")
    w(f'<p>{head("layers", "01 — Every layer")}</p>\n<p>{img("layers.svg", ALT["layers"])}</p>\n<br>\n')
    w(f'<p>{head("card", "02 — Model card")}</p>\n<p>{img("modelcard.svg", ALT["modelcard"])}</p>\n<br>\n')
    w(f'<p>{head("skills", "03 — Skill space")}</p>\n<p>{img("embed.svg", ALT["embed"])}</p>\n<br>\n')
    w(f'<p>{head("prod", "04 — In production")}</p>\n'
      f'<p><a href="{C.LANGUAGE_METRICS}">{img("experience.svg", ALT["experience"])}</a></p>\n<br>\n')
    w(f'<p>{head("evidence", "05 — Evidence")}</p>\n<p>{img("evidence.svg", ALT["evidence"])}</p>\n')
    w(f'<p align="center"><b><a href="{r("mandateos")}">MandateOS</a></b> (<a href="{C.LIVE["mandateos"]}">live</a>) · '
      f'<b><a href="{r("clauseguard")}">ClauseGuard</a></b> (<a href="{C.LIVE["clauseguard"]}">live</a>) · '
      f'<a href="{r("knowledge-agent")}">Knowledge-Agent</a> · <a href="{r("truebrain")}">TrueBrain</a> · '
      f'<a href="{r("promptforge")}">PromptForge</a> · <a href="{r("drishti")}">Drishti</a></p>\n<br>\n')
    w(f'<p>{head("activity", "06 — Activity")}</p>\n<p>{img("skyline.svg", ALT["skyline"])}</p>\n<br>\n')
    w(f'<p>{head("contact", "07 — Prompt me")}</p>\n<p><a href="{mail}">{img("footer.svg", ALT["footer"])}</a></p>\n')
    w('<p align="center"><sub>Every image here is generated from source in <a href=".github/profile">.github/profile</a>: '
      'real fonts turned into outlines, pure-CSS animation, an activity city that syncs daily, and no third-party widgets.</sub></p>\n')
    readme = "\n".join(out)
    with open(os.path.join(ROOT, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)
    print(f"  README.md                        {len(readme.encode())/1024:6.1f} KB")
    return []
